[Gen 3] Hustle reduces accuracy of moves by type
smogon/pokemon-showdown pull request #10168
Opened 2024-02-12 15:02 UTC by tmagicturtle

Recognizing that keeping `move.category === 'Physical'` MIGHT be redundant.

https://www.smogon.com/forums/threads/gen-3-hustle-should-affect-status-moves-accuracy.3735326/
In Gen 3, Hustle reduces the accuracy of physical-typed Status category moves.

2024-02-13 05:24 UTC, DaWoblefet commented
Looks like Hidden Power's interaction with Hustle on this one has behavior where the effective type is considered and not just Normal (unlike say, Counter). Which is good because we don't need to check the original typing.

2024-02-13 05:26 UTC, DaWoblefet requested changes

2024-02-13 05:26 UTC, DaWoblefet commented on data/mods/gen3/abilities.ts
> +			if (move.category === 'Physical' || physicalTypes.includes(move.type)) {
You can drop the category check, you'll produce the same list either way. One that you need to add back is ``typeof accuracy === 'number'`` so you can't miss things like Block or Helping Hand.

2024-02-13 13:14 UTC, tmagicturtle commented
> Looks like Hidden Power's interaction with Hustle on this one has behavior where the effective type is considered and not just Normal (unlike say, Counter). Which is good because we don't need to check the original typing.

This seemed to be the case when I reviewed it! Thank you for the confirmation!

2024-02-13 14:41 UTC, tmagicturtle reviewed
Changes made

2024-02-15 04:28 UTC, merged

2024-02-15 04:28 UTC, DaWoblefet commented
Thanks fart!