Scavenger Hunt Bug fix
smogon/pokemon-showdown pull request #10331
Opened 2024-06-03 14:46 UTC by Vinayak-Shukla

Once a user finished a hunt, upon refresh, they would get the scavenger hunt added back to their games list since they're present in the playerTable. Adding a check during RejoinGames to ignore players who're in scavengers and have completed the current game/hunt.

2024-06-03 17:13 UTC, PartMan7 commented
Yo @mia-pi-git would it be fine to add a generic property for this (player.noReconnect or game.noReconnectOnFinish or something, or even just player.completed) instead of a hardcoded check for Scavs here? An issue is that this won't cover hunts from, say, Treasure Town (alternatively this could probably check the game type)

2024-06-03 17:48 UTC, Vinayak-Shukla commented
I wasn't a 100% sure if gameid/game remains the same for all the various twists we do which is why I ultimately went with roomid, where I missed TTT hunts true, but yeah we can use game/gameid instead too

2024-06-03 20:33 UTC, Vinayak-Shukla commented
Have fixed the lint errors

2024-06-04 03:27 UTC, PartMan7 reviewed
Oki looks good now (still requires discussion about whether the approach is alright)

2024-06-04 04:48 UTC, mia-pi-git commented
> Yo @mia-pi-git would it be fine to add a generic property for this (player.noReconnect or game.noReconnectOnFinish or something, or even just player.completed) instead of a hardcoded check for Scavs here? An issue is that this won't cover hunts from, say, Treasure Town (alternatively this could probably check the game type)

Yes, this would be much more ideal as a solution. Hardcoding it for a specific roomid will, in all likelyhood, play very poorly with other roomgames.

2024-06-04 16:59 UTC, Vinayak-Shukla commented
Have removed the specific room id, only kept a generic player.completed check, this should be fine I hope

2024-06-05 04:46 UTC, PartMan7 requested changes
Could you add a comment here explaining why the check is used? (something like `Prevents players from games like Scavengers from being re-added even after finishing`)

2024-06-05 07:43 UTC, Vinayak-Shukla commented
done

2024-06-09 04:05 UTC, PartMan7 approved these changes

2024-06-16 20:24 UTC, mia-pi-git commented on server/rooms.ts
> +			if (player.completed) continue; //Prevents players from being re-added to games like Scavengers after they've finished
This needs a corresponding type declaration in the RoomGamePlayer class.

2024-06-16 20:41 UTC, Vinayak-Shukla commented
added type declaration @mia-pi-git

2024-06-16 21:43 UTC, singiamtel commented
Doesn't pass the linting for me, make sure to run ``npm run lint`` and fix the issues before pushing

2024-06-16 23:51 UTC, mia-pi-git commented on server/room-game.ts
> +	completed: boolean;
```suggestion
	completed?: boolean;
```
I would probably make this optional.

2024-06-16 23:52 UTC, mia-pi-git commented on server/room-game.ts
> +		this.completed = false;
```suggestion
```

2024-06-17 12:26 UTC, Vinayak-Shukla commented
have done the changes, it should be good now @mia-pi-git

2024-06-17 17:12 UTC, Vinayak-Shukla commented
could you explain what tests are exactly failing im not too familiar with node and so on

2024-06-17 17:14 UTC, merged