Scavengers HTML Hunts
smogon/pokemon-showdown pull request #10414
Opened 2024-07-11 21:37 UTC by Lucas-Meijer

As discussed with Computerwizard8800, aQrator, and Scavengers roomstaff.

Implementation of HTML for Scavengers hunts, similar to HTML in viewrepeats.
Also adds maximum size for Scavengers hunts, to avoid images being too large.

2024-07-11 22:54 UTC, aQrator commented
Confirming approval

2024-07-12 06:13 UTC, KrisXV commented on server/chat-plugins/mafia.ts
> +	alignments: { [k: string]: MafiaDataAlignment };
can you undo all of these

2024-07-12 06:16 UTC, PartMan7 commented on server/chat-plugins/scavengers.ts
> +		room.game = new ScavengerHunt(room, user, hosts, gameType, res.result, isHTML, mod);
The class is starting to have a bit too many arguments; could you make this a destructured parameter instead?

2024-07-12 06:17 UTC, PartMan7 commented on server/chat-plugins/scavengers.ts
> +		this.isHTML = isHTML ? isHTML : false;
Any reason why this isn't just `this.isHTML = isHTML` or `this.isHTML = !!isHTML`?

2024-07-12 06:18 UTC, PartMan7 commented on server/chat-plugins/scavengers.ts
> +				isHTML: this.cmd.includes('html'),
If the isHTML from line 1744 is still in scope, probably reuse that here

2024-07-12 06:23 UTC, PartMan7 commented
Could you also check the cases in `scavenger-games.ts` where we send HTML? `onShowEndBoard` for Minesweeper is an example that would need to be handled.

2024-07-16 18:31 UTC, PartMan7 requested changes
Whoops, sorry this took me a while to get to.

2024-07-16 18:31 UTC, PartMan7 commented on server/chat-plugins/scavengers.ts
> +			`<div style="border:1px solid #CCC;padding:4px 6px;margin:4px 1px; overflow:scroll; max-height: 50vh">` +
Could you add a similar %-based value for max-width? Currently, images overflow horizontally (you've already handled the vertical cases).

2024-07-16 18:31 UTC, PartMan7 commented on server/chat-plugins/scavenger-games.ts
> +								`|raw|<strong>The first hint to the next hunt is:</strong> ${this.isHTML ? this.questions[0].hint : Chat.formatText(this.questions[0].hint)}`
Would wrap handling be needed for these?

2024-07-16 18:31 UTC, PartMan7 commented on server/chat-plugins/scavengers.ts
> +	let template = `<div class="ladder" style="overflow:scroll; max-height: 50vh"><table style="width: 100%"><tr><th>By</th><th>Questions</th></tr>${showStaff ? buffer : buffer.replace(/<button.*?>.+?<\
Re: both /scav queue and /viewhunt, could you make the wrap apply on each row as opposed to the full table? If Q1 has an overflowing image, the other questions are shoved out of view.

2024-08-19 05:27 UTC, PartMan7 approved these changes
Looks great; thanks!

2024-08-21 20:50 UTC, HoeenCoder reviewed
Excellent work overall, one thing I noticed to consider.

2024-08-21 20:50 UTC, HoeenCoder commented on server/chat-plugins/scavengers.ts
> +			`<strong><em>Hint #1:</em> ${this.isHTML ? this.questions[0].hint : Chat.formatText(this.questions[0].hint)}</strong>` +
I see a large number of very similar statements in the form of `this.isHTML ? text : Chat.formatText(text)`. Have you considered modularizing this? More specifically make a method such as:
```typescript
formatOutput(text: string): string {
	return this.isHTML ? text : Chat.formatText(text);
}
```

I will mention I do see some of these statements using Utils.escapeHTML instead, evaluate which method you want to use within the proposed method.

2024-08-21 23:33 UTC, mia-pi-git approved these changes
Make the change Hoeen suggested and tag me when you're done, I'll merge this. LGTM otherwise.

2024-08-21 23:48 UTC, Lucas-Meijer commented
> Make the change Hoeen suggested and tag me when you're done, I'll merge this. LGTM otherwise.

@mia-pi-git it's ready!

2024-08-21 23:49 UTC, mia-pi-git commented on server/chat-plugins/scavengers.ts
> +							return item.isHTML ? q : Utils.escapeHTML(q);
```suggestion
							return item.formatOutput(q);
```

2024-08-21 23:50 UTC, mia-pi-git commented on server/chat-plugins/scavengers.ts
> +							return item.isHTML ? q : Utils.escapeHTML(q);
Oh, actually, you can ignore this. Went and poked at it a bit to be sure.

2024-08-21 23:51 UTC, merged