Mafia Search capability
smogon/pokemon-showdown pull request #10682
Opened 2024-11-19 21:46 UTC by Lucas-Meijer

Overhauls the 'mafia listdata' command, to instead show data in a neater way. Allows for the user to search within the various Mafia data categories, and also generate random data, like the 'ds' command.

Collaboration with @Alexander489

Replaces https://github.com/smogon/pokemon-showdown/pull/10467

2025-06-09 23:20 UTC, HoeenCoder requested changes
You have quite a bit of difficult to read code. Its not that its impossible to understand, its just that its pretty dense and takes time to understand. This makes it harder to maintain the code for both you and others. I recommend adding comments explaining what your more dense sections are doing (I added review notes to a few of these, but there are many places such as where you do `entries = entries.filter...`).

2025-06-09 23:20 UTC, HoeenCoder commented on server/chat-plugins/mafia.ts
> +		if (!inequality) return entries; // this.errorReply(`Please provide a valid inequality for the players.`);
Leftover commented out code maybe?

2025-06-09 23:20 UTC, HoeenCoder commented on server/chat-plugins/mafia.ts
> +			!isNaN(Number(players)))) {
```suggestion
		if (!!players && !isNaN(Number(players))) {
```

This is easier to understand, assuming your goal here is for this to execute if and only if players is a number (in a string).

2025-06-09 23:20 UTC, HoeenCoder commented on server/chat-plugins/mafia.ts
> +					.some(playerCount => playerCount in (MafiaData[`themes`][key])));
Why `+players`?

I recommend adding one or more comments here to explain whats going on to increase code readability and make maintenance easier.

2025-06-09 23:20 UTC, HoeenCoder commented on server/chat-plugins/mafia.ts
> +					.some(playerCount => playerCount in (MafiaData[`themes`][key])));
See my comment on L177.

2025-06-09 23:20 UTC, HoeenCoder commented on server/chat-plugins/mafia.ts
> +				searchType = `aliases`;
Lets apply D.R.Y. (Don't Repeat Yourself) to this.

Use a loop instead eg:
```suggestion
			const searchTypes = ['themes', 'roles', ...];
			for (const type of searchTypes) {
				if (cmd.includes(type) || targets.includes(type)) {
					searchType = type;
					if (targets.includes(type)) targets.splice(targets.indexOf(type), 1);
				}
			}
```

Don't use this exact suggestion as you'll need to adjust to handle random search types too. Any time you find yourself using the same code over and over with small adjustments, you should be looking for a way to use a loop instead (or similar).

2025-06-09 23:20 UTC, HoeenCoder commented on server/chat-plugins/mafia.ts
> +					!isNaN(Number(targets[i].toString())))) {
See what I said about L172.

2025-06-09 23:20 UTC, HoeenCoder commented on server/chat-plugins/mafia.ts
> +			// TODO: hide certain roles from appearing (unless the command includes the 'hidden' parameter)
Just checking that this note is intended to be here.

2025-06-11 20:30 UTC, Snaq-PS commented on server/chat-plugins/mafia.ts
> +			// TODO: hide certain roles from appearing (unless the command includes the 'hidden' parameter)
It is indeed! (If that's okay) It's a feature we desire but decided to push out of scope for this PR.

2025-06-11 20:42 UTC, Lucas-Meijer commented on server/chat-plugins/mafia.ts
> +					.some(playerCount => playerCount in (MafiaData[`themes`][key])));
+players ensures that it is read as a number, not a character

Adding this as a comment, as well

2025-08-10 17:52 UTC, merged