Chat: Refactor permission checking functions to use ErrorMessage
smogon/pokemon-showdown pull request #7234
Opened 2020-08-20 09:53 UTC by mia-pi-git

This makes `CommandContext.can` and `PageContext.can` into functions that use `Chat.ErrorMessage`, so that instead of 
```ts
if (!this.can('lock')) return false;
``` 
you can just add, say, 
```ts
this.checkPermission('lock');
```
to the command, and it will throw the access denied message if they can't use it. It also still returns true, so you can still use it as part of an if statement where it checks something else in addition to the permission, but this will make it easier to use.
Likewise, `CommandContext.privatelyCan` was also renamed to `CommandContext.privatelyCheckPermission`, and `CommandContext.canUseConsole` was also edited to use `ErrorMessage`.
(I also removed the Utils.html in `PageContext.send`, so that HTML can be used in errors - if that's something people disagree with, i'll remove it, but i feel like the pages should be sanitizing the errors on their own, if necessary.)

2020-09-05 19:52 UTC, AnnikaCodes requested changes
PMd you on Discord like you asked.

2020-09-06 04:07 UTC, Zarel commented on server/chat.ts
> +CommandContext.prototype.canEmbedURI = CommandContext.prototype.checkEmbedURI;
I think you should also add `requiresRoom` to these.

2020-09-06 04:08 UTC, Zarel commented on server/chat.ts
> +CommandContext.prototype.canEmbedURI = CommandContext.prototype.checkEmbedURI;
And `checkPMHTML` and `privatelyCheck`... actually can you just make sure you alias all the ones that make sense to alias?

2020-09-06 07:15 UTC, merged

2020-09-06 07:15 UTC, Zarel commented
Thanks!

I'll wait until tomorrow to hotpatch since I need to sleep now, but it looks good.