Make Galar formes show up in /ds
smogon/pokemon-showdown pull request #7447
Opened 2020-10-01 03:26 UTC by ZardMX

2020-10-01 03:28 UTC, AnnikaCodes requested changes

2020-10-01 03:28 UTC, AnnikaCodes commented on server/chat-plugins/datasearch.ts
> +		const isAlolaORGalar = (dex[mon].forme === "Galar" || dex[mon].forme === "Alola") && dex[mon].name !== "Pikachu-Alola";
```suggestion
		const isRegionalForm = (dex[mon].forme === "Galar" || dex[mon].forme === "Alola") && dex[mon].name !== "Pikachu-Alola";
```

2020-10-01 03:28 UTC, AnnikaCodes commented on server/chat-plugins/datasearch.ts
> +		if (!isAlolaORGalar && dex[mon].baseSpecies && results.includes(dex[mon].baseSpecies)) continue;
```suggestion
		if (!isRegionalForm && dex[mon].baseSpecies && results.includes(dex[mon].baseSpecies)) continue;
```

2020-10-10 02:48 UTC, ZardMX commented
bump?

2020-10-18 11:36 UTC, Zarel commented
@AnnikaCodes do you approve this now?

2020-10-18 15:45 UTC, AnnikaCodes approved these changes
Looks fine to me.

2020-10-19 10:19 UTC, merged

2020-10-19 10:19 UTC, Zarel commented
Thanks!