Hangman: Support saving hangman entries
smogon/pokemon-showdown pull request #7630
Opened 2020-11-03 19:35 UTC by mia-pi-git

Requested.

2020-11-04 01:47 UTC, KrisXV requested changes
Unless I misinterpreted the suggestion, I think the requester wanted to be able to synchronously create a hangman and save it to a database for future use

2020-11-04 01:47 UTC, KrisXV commented on server/chat-plugins/hangman.ts
> +export let hangmanData: {[roomid: string]: {[question: string]: string[]}} = {};
```suggestion
export let hangmanData: {[roomid: string]: {[phrase: string]: string[]}} = {};
```

this should be formatted as
```javascripts
roomid: {
	"this is a phrase": ["this is a possible hint", "this is another hint for the same phrase"],
	"this is another phrase": ["this is a possible hint", "this is another hint for the same phrase"],
},
```

2020-11-04 01:47 UTC, KrisXV commented on server/chat-plugins/hangman.ts
> +			const {word} = Hangman.validateParams(args);
```suggestion
			const {phrase} = Hangman.validateParams(args);
```

2020-11-04 01:47 UTC, KrisXV commented on server/chat-plugins/hangman.ts
> +			const args = target.split(',');
```suggestion
			const args = target.split('|');
```

some people might want hints with commas in them

2020-11-04 01:53 UTC, mia-pi-git commented
> Unless I misinterpreted the suggestion, I think the requester wanted to be able to synchronously create a hangman and save it to a database for future use

They said they wanted it the same as kid a - which saved them without creating one. https://www.smogon.com/forums/threads/hangmans-save.3671044/

2020-11-04 02:07 UTC, KrisXV approved these changes

2020-12-02 22:24 UTC, mia-pi-git commented
@Zarel bump

2020-12-27 06:11 UTC, Zarel commented
:s

I suppose the memory impact isn't big...

2021-01-28 18:46 UTC, Zarel commented on server/chat-plugins/hangman.ts
> +		const shuffled = Utils.shuffle(Object.keys(hangmanData[room]))[0];
```suggestion
		const shuffled = Utils.randomElement(Object.keys(hangmanData[room]));
```

2021-01-28 18:47 UTC, Zarel commented on server/chat-plugins/hangman.ts
> +			hint: Utils.shuffle(hints)[0],
```suggestion
			hint: Utils.randomElement(hints),
```

2021-01-28 18:57 UTC, Zarel commented on lib/utils.ts
> +	}
Please no!

2021-01-28 18:57 UTC, Zarel commented on lib/utils.ts
> +	}
```suggestion
	randomElement<T>(arr: T[]): T {
		const i = Math.floor(Math.random() * arr.length);
		return arr[i];
	}
```

2021-01-28 18:58 UTC, mia-pi-git commented on lib/utils.ts
> +	}
lol this is what i did originally

2021-01-28 19:24 UTC, merged

2021-01-28 19:24 UTC, Zarel commented
ty!