Add missing command in /h poll
smogon/pokemon-showdown pull request #7803
Opened 2020-12-14 20:10 UTC by Distrib-ps

Hey ! PR for https://www.smogon.com/forums/threads/missing-command-from-h-poll.3674791/

2020-12-14 20:12 UTC, AnnikaCodes commented
This help is really long; maybe we should tuck it into a readmore?

2020-12-14 20:16 UTC, Distrib-ps commented
Yes, I think it will be better.

2020-12-15 11:43 UTC, sirKiraUzumaki requested changes

2020-12-15 11:43 UTC, sirKiraUzumaki commented on server/chat-plugins/poll.ts
> +			`<p><code>/poll clearqueue </code>- Deletes the queue of polls. Requires: % @ # &.<br />` +
```suggestion
			`<p><code>/poll htmlcreate(multi) [question], [option1], [option2], [...]</code> - Creates a poll, with HTML allowed in the question and options. Requires: # &<br />` +
			`<p><code>/poll vote [number]</code> - Votes for option [number].<br />` +
			`<p><code>/poll timer [minutes]</code> - Sets the poll to automatically end after [minutes]. Requires: % @ # &.<br />` +
			`<p><code>/poll results</code> - Shows the results of the poll without voting. NOTE: you can't go back and vote after using this.<br />` +
			`<p><code>/poll display</code> - Displays the poll.<br />` +
			`<p><code>/poll end</code> - Ends a poll and displays the results. Requires: % @ # &.<br />` +
			`<p><code>/poll queue [question], [option1], [option2], [...]</code> - Add a poll in queue. Requires: % @ # &<br />` +
			`<p><code>/poll deletequeue [number]</code> - Deletes poll at the corresponding queue slot (1 = next, 2 = the one after that, etc).<br />` +
			`<p><code>/poll clearqueue</code> - Deletes the queue of polls. Requires: % @ # &.<br />` +
```
Just a small suggestion to make it look more formal and neat.

2020-12-16 07:27 UTC, AnnikaCodes commented on server/chat-plugins/poll.ts
> +		);
You should remove the `<p>` tags here.

2020-12-16 16:47 UTC, AnnikaCodes approved these changes

2020-12-21 21:55 UTC, merged

2020-12-22 05:12 UTC, Zarel commented
I think it's important for commands not to be useless without clicking "read more" – Design Standard 3: https://github.com/smogon/pokemon-showdown/blob/master/CONTRIBUTING.md#design-standards

It makes sense to bring `/poll create` above the fold.

2020-12-22 05:13 UTC, AnnikaCodes commented
If we're doing that then `/h daily` and `/h dc` should also be changed

2020-12-22 05:31 UTC, Zarel commented
c13a9c84fbca11a2 may be good to look for reference, if you want to change `/h daily` and `/h dc`