Fix spinlock in /nomarkshared view
smogon/pokemon-showdown pull request #7821
Opened 2020-12-18 20:03 UTC by mia-pi-git

2020-12-18 21:04 UTC, AnnikaCodes requested changes

2020-12-18 21:05 UTC, AnnikaCodes requested changes

2020-12-18 21:05 UTC, AnnikaCodes commented on server/ip-tools.ts
> +			diff = (aPart || 0) - (bPart || 0);
```suggestion
			diff = aPart - bPart;
```
parseInt returns an integer or NaN, nothing falsy except 0

2020-12-18 21:15 UTC, AnnikaCodes approved these changes
Thanks!

2020-12-18 21:16 UTC, merged

2020-12-21 00:32 UTC, Zarel commented on server/chat-plugins/hosts.ts
> +			sortedSharedIPBlacklist.sort((a, b) => IPTools.ipSort(a[0], b[0]));
Should probably be `ipCompare`? Also I wonder if `sortBy` would be easier?

2020-12-21 00:33 UTC, Zarel commented on server/chat-plugins/hosts.ts
> +			sortedSharedIPBlacklist.sort((a, b) => IPTools.ipSort(a[0], b[0]));
```ts
Utils.sortBy(sortedSharedIPBlacklist, ip => ip.split('.').map(octet => parseInt(octet)));
```