Random Battles: Refactor for code standards and readability
smogon/pokemon-showdown pull request #8021
Opened 2021-02-12 04:42 UTC by AnnikaCodes

This PR
- Brings all Random Battles code up to the standard 120-charaacter line length limit
- Improves readability for all Random Battles code
- Refactors current-gen Random Battles team generation to be more modular and readable

Ideas for the future:
- Further refactors (I'm waiting on this until I'm more familiar with the codebase)
- Possibly adding unit tests
- Ideally, properly divorcing code and data like Battle Factory has

cc @KrisXV @ACakeWearingAHat

2021-02-12 16:48 UTC, AnnikaCodes commented on data/mods/gen4/random-teams.ts
> +				) {
Yeah, there is. In the current generation, I refactored each line into its own `moveRejectionChecker`. I'm planning to refactor the old generations at some point, but I want to see how the current-gen refactor goes first (I just don't like the randbats code having a ridiculously long `max-len` setting).

2021-02-12 16:49 UTC, AnnikaCodes commented on data/mods/gen3/random-teams.ts
> +				'Liechi Berry';
Yeah that's fair tbh, I'll change those around.

2021-02-12 16:53 UTC, AnnikaCodes commented on data/mods/gen5/random-teams.ts
> +				) {
The rubric I used was that if a line didn't fit I broke it up, trying to group together similar conditions.

2021-02-12 16:58 UTC, AnnikaCodes commented on data/mods/gen6/random-teams.ts
> +						(restTalk) ||
Yeah, that's on me. I'll fix it.

2021-02-12 17:04 UTC, AnnikaCodes commented on data/random-teams.ts
> +	}
I'm not entirely sure what the point of this either; it's just extracting https://github.com/smogon/pokemon-showdown/blob/master/data/random-teams.ts#L997 out into a method. It should be moves that _aren't_ in the Array literal, though, so I fixed that and I gave it a less pretentious name.

2021-02-12 17:04 UTC, AnnikaCodes commented on data/random-teams.ts
> +				];
Sounds like a good idea!

2021-02-12 17:05 UTC, AnnikaCodes commented on data/random-teams.ts
> +			if (StatDroppingMoves.includes(moveid)) counter.contrary++;
That's fine; my preference for it was quite minimal and I'm happy to change it back.

2021-02-12 17:07 UTC, AnnikaCodes commented on data/mods/gen7/random-teams.ts
> +					) || (hasType['Electric'] && (!counter['Electric'] || movePool.includes('thunder'))) ||
I'm planning to get rid of the gargantuan `if` statements altogether; this is just a temporary stopgap measure so we can stop making exceptions with `eslint`.

2021-02-12 23:15 UTC, ACakeWearingAHat requested changes
Add comments specifying hardcoded move-cull lines and their reasonings

2021-02-12 23:15 UTC, ACakeWearingAHat commented on data/random-teams.ts
> +			return {cull: hasMove['knockoff']};
```suggestion
			// Special case for Dhelmise in Doubles, which doesn't want both
			return {cull: hasMove['knockoff']};
```
honestly just remove this and remove poltergeist from dhelm and that'd be fine too. simpler, not much impact. poltergeist sucks in doubles anyway

2021-02-12 23:15 UTC, ACakeWearingAHat commented on data/random-teams.ts
> +			return {cull: movePool.includes('extremespeed')};
```suggestion
			// Special case for Lucario, which always wants Extreme Speed.
			return {cull: movePool.includes('extremespeed')};
```
rejected move should probably be ice punch and not this but that's a discussion for later

2021-02-12 23:15 UTC, ACakeWearingAHat commented on data/random-teams.ts
> +			return {cull: hasMove['voltswitch']};
```suggestion
			// Special case for Xurkitree to properly split Blunder Policy and Choice item sets
			return {cull: hasMove['voltswitch']};
```

2021-02-12 23:15 UTC, ACakeWearingAHat commented on data/random-teams.ts
> +			return {cull: !teamDetails.stealthRock && (hasMove['stealthrock'] || movePool.includes('stealthrock'))};
```suggestion
			// Special case for Corsola-Galar, which always wants Will-O-Wisp
			return {cull: !teamDetails.stealthRock && (hasMove['stealthrock'] || movePool.includes('stealthrock'))};
```

2021-02-12 23:15 UTC, ACakeWearingAHat commented on data/random-teams.ts
> +			return {cull: hasMove['throatchop'] || (hasMove['stoneedge'] && !hasType['Rock'])};
```suggestion
			// Special case for Hawlucha, which doesn't want Roost + 3 attacks
			return {cull: hasMove['throatchop'] || (hasMove['stoneedge'] && !hasType['Rock'])};
```

2021-02-12 23:15 UTC, ACakeWearingAHat commented on data/random-teams.ts
> +			return {cull: hasMove['acupressure']};
```suggestion
			// Special case for Shuckle in Doubles, which doesn't want sets with no method to harm foes
			return {cull: hasMove['acupressure']};
```

2021-02-12 23:22 UTC, AnnikaCodes commented on data/random-teams.ts
> +			return {cull: hasMove['rapidspin'] || hasMove['taunt']};
I would like this PR to not change functionality, but we can talk about how best to change this - Morpeko could be directly hardcoded.

2021-02-12 23:23 UTC, AnnikaCodes commented on data/random-teams.ts
> +			return {cull: hasMove['aquajet'] || counter.Status};
See my comment re: Morpeko

2021-02-12 23:50 UTC, merged

2021-02-15 09:43 UTC, Zarel commented
<3