Random Battles: Refactor Gen 5 and Gen 6
smogon/pokemon-showdown pull request #8106
Opened 2021-03-07 22:56 UTC by AnnikaCodes

As usual, no change in teams from 10,000 different seeds

2021-03-07 23:21 UTC, ACakeWearingAHat requested changes
just consolidating scarf requirements into a const real quick

2021-03-07 23:21 UTC, ACakeWearingAHat commented on data/mods/gen6/random-teams.ts
> +		const defensiveStatTotal = species.baseStats.hp + species.baseStats.def + species.baseStats.spd;
```suggestion
		const defensiveStatTotal = species.baseStats.hp + species.baseStats.def + species.baseStats.spd;
		const scarfReqs = species.baseStats.spe >= 60 && species.baseStats.spe <= 108 && !counter.priority
```

2021-03-07 23:21 UTC, ACakeWearingAHat commented on data/mods/gen6/random-teams.ts
> +				!counter.priority && this.randomChance(2, 3)
```suggestion
				species.baseStats.spa >= 100 &&
				scarfReqs &&
				this.randomChance(2, 3)
```

2021-03-07 23:21 UTC, ACakeWearingAHat commented on data/mods/gen6/random-teams.ts
> +			!counter.priority &&
```suggestion
			scarfReqs &&
```

2021-03-07 23:21 UTC, ACakeWearingAHat commented on data/mods/gen6/random-teams.ts
> +				!counter.priority &&
```suggestion
				scarfReqs &&
```

2021-03-10 00:37 UTC, Zarel approved these changes
I don't see any problems with this; I'll let you decide how you want to handle this. You don't need my approval for working on random battles, in case that wasn't clear.

2021-03-10 03:49 UTC, AnnikaCodes commented
I wasn't awaiting your approval; just making a PR since it's a major change and I want to give others a chance to provide feedback and get more pairs of eyes on the code (which could include you, but in practice is Kris, pyuk, and Cake).

2021-03-10 03:49 UTC, merged