Granular Room Permissions Settings
smogon/pokemon-showdown pull request #8365
Opened 2021-06-13 01:46 UTC by tmagicturtle

Hi, I thought it would be useful for /permissions to be able to turn on/off command options for each rank, rather than setting a minimum. In particular this would be useful for Bots, since (by good reason) they are ranked below Drivers, but would benefit from additional permissions like auto-moderation, Room/Staff intro modification (Officer Jenny does this for tracking watchlisted users for promotions in staff intros), and other useful commands.

My one concern is in the implementation of the user-groups.ts#hasPermission function. I am not sure what the jurisdiction thing is about (a room/global issue?) so I am not sure if simply returning the value of the room permission introduces a security risk. I would like some assistance here (and obviously if this is fine I would remove the non-executed code below it). Any assistance would be appreciated.

2021-06-13 01:48 UTC, mia-pi-git commented on server/user-groups.ts
> +					return roomPermissions[`/${cmd}`][symbol];
Does returning here work? It shouldn't. 
You may want to check 
```ts
if ((roomPermissions[`/${cmd}`][symbol] && auth.get(user) !== roomPermissions[`/${cmd}`][symbol]) || !auth.atLeast(user, roomPermissions[`/${cmd}`])) return false```

2021-06-13 01:49 UTC, mia-pi-git commented on server/user-groups.ts
> +					return roomPermissions[`/${cmd}`][symbol];
(That's long, yes, but it should work more generally.)

2021-06-13 01:51 UTC, mia-pi-git requested changes

2021-06-13 01:51 UTC, mia-pi-git commented on server/user-groups.ts
> +					return roomPermissions[`/${cmd}`][symbol];
Presently, this looks like it breaks other custom permissions.

2021-06-13 01:59 UTC, Zarel commented
I would really prefer not to have them be so granular without a better reason...

2021-06-13 02:01 UTC, Zarel commented
If literally the only use for this huge amount of code complexity is bots, perhaps we should consider either moving bots up, or hardcoding them in some way.

2021-06-13 02:02 UTC, mia-pi-git commented
> If literally the only use for this huge amount of code complexity is bots, perhaps we should consider either moving bots up, or hardcoding them in some way.

We've moved them up before, down before, up before, and now down to here. i don't think moving is necessarily the solution.

2021-06-13 02:03 UTC, Zarel commented
Yeah, I know; I just went and looked at the comment because this has come up before:

```
// Bots are ranked below Driver/Mod so that Global Bots can be kept out
// of modjoin % rooms (namely, Staff).
// (They were previously above Driver/Mod so they can have game management
// permissions drivers don't, but these permissions can be manually given.)
```

I think the correct action here is to hardcode giving bots all permissions with a custom permission set.

2022-07-21 02:31 UTC, AnnikaCodes commented
@tmagicturtle, are you planning to do more work on this PR?

2022-07-26 08:08 UTC, tmagicturtle commented
No, I suppose not. Sorry for leaving it open, I'll close it now.

2022-07-26 08:08 UTC, closed without merging