Chat: Add an onConfigRefresh handler
smogon/pokemon-showdown pull request #8529
Opened 2021-11-15 15:16 UTC by mia-pi-git

Takes hardcodes out of the main index file, plus lets other plugins hook into config. This is only a PR because it needs a restart.

2021-11-15 21:41 UTC, Zarel commented
I'm going to need way more details on what this is for.

2021-11-15 21:43 UTC, Zarel commented
Oh, I think I understand.

Hm, should chat plugins be hooking into Config at all? In theory chat plugin configuration is handled inside every chat plugin. We might need to rearchitect how configuration works at all, if chat plugins have need for it.

2021-11-15 21:44 UTC, mia-pi-git commented
> Oh, I think I understand.
> 
> Hm, should chat plugins be hooking into Config at all? In theory chat plugin configuration is handled inside every chat plugin. We might need to rearchitect how configuration works at all, if chat plugins have need for it.

It's not to configure a plugin tbc; the plugin exists to help non-sim3 admins modify a relevant part of the config.

2021-11-15 21:44 UTC, Zarel commented on server/chat-plugins/username-prefixes.ts
> +		// by battle prefixes manually specified in config.js
What battle prefixes are manually specified in config.js? If they're related, maybe it should be stored in the same place the chat plugin's own data is?

2021-11-15 21:45 UTC, Zarel commented
If people without server access want to modify config, that data should probably be moved out of `config.js`.

2021-11-15 23:37 UTC, Zarel requested changes
I think a single-line hardcode is better than an entire system that should never be used.

2021-11-16 18:45 UTC, AnnikaCodes commented
Battle prefixes used to be stored in `config.js` - we can probably remove the functionality to load from config.js (or at least deprecate it and remove this hook), since most battle prefixes are now stored in a JSON configuration file.

2021-11-17 18:53 UTC, Zarel commented
> I agree that chat plugins shouldn't modify config.js, but that's not what's happening here.

Yeah, I was confused by that, but I was just going off Mia saying "plugin exists to help non-sim3 admins modify a relevant part of the config".

My main issue is still that I think any setting that plugins would want to listen to should be kept out of config.js.

...We should probably move custom avatars out of config.js, incidentally.

2022-07-21 02:18 UTC, AnnikaCodes commented
Is this still necessary? Battle prefixes aren't in Config anymore, and I agree with Zarel that settings that need to be changed by people without access to sim3 should be in separate files anyway.

2022-07-21 02:18 UTC, mia-pi-git commented
Yeah, it's not.

2022-07-21 02:18 UTC, closed without merging