Gen 9 Random Battle: Improve handling of lead slot
smogon/pokemon-showdown pull request #9494
Opened 2023-04-04 01:44 UTC by MathyFurret

Previously, Pokemon that shouldn't be put in the lead slot were simply skipped. Now they are still added, but a different lead is chosen on the next iteration and inserted in front.

2023-04-04 08:16 UTC, livid-washed requested changes
Each Pokemon set is being included twice

2023-04-04 08:16 UTC, livid-washed commented on data/random-teams.ts
>  			// Okay, the set passes, add it to our team
```suggestion
```

2023-04-04 08:16 UTC, livid-washed commented on data/random-teams.ts
>  			pokemon.push(set);
```suggestion
```

2023-04-04 14:51 UTC, mia-pi-git commented on data/random-teams.ts
> +const NoLeadPokemon = [
```suggestion
const noLeadPokemon = [
```

2023-04-04 14:51 UTC, mia-pi-git commented on data/random-teams.ts
>  const PriorityPokemon = [
```suggestion
const priorityPokemon = [
```
camelCase :[

2023-04-10 21:27 UTC, adrivrie commented
This change was merged into #9510 so I think this can be closed, but ty mathy :)

2023-04-10 21:39 UTC, closed without merging