Adding Pet Mod of the Season, [Gen 3] Hoenn Gaiden
smogon/pokemon-showdown pull request #9690
Opened 2023-08-01 06:18 UTC by Yoshiblaze

Hello!

This PR is for adding Hoenn Gaiden to the server as the (long, LONG overdue) Pet Mod of the Season. Another PR for the same purpose was made earlier by Yak Attack, but this one has many notable differences, mainly being more concise and lacking some unnecessary files. 

Any questions can be directed towards Rezzo, Yak Attack, or myself. 

https://www.smogon.com/forums/threads/hoenn-gaiden-pet-mod-of-the-season.3714737/
https://www.smogon.com/forums/threads/hoenn-gaiden-is-gen-9s-first-pet-mod-of-the-season.3716671/ (Decided all the way back in February)

2023-08-06 23:40 UTC, KrisXV requested changes
please fix all the build errors

2023-08-06 23:40 UTC, KrisXV commented on config/formats.ts
> +		desc: ["<b>Hoenn Gaiden</b>: A Gen 3 pet mod that aims to devamp Gen 4-8 Pokemon, moves and items into the Gen 3 mechanics."],
```suggestion
		desc: `A Gen 3 Pet Mod that aims to devamp Gen 4-8 Pok&eacute;mon, moves, and items into the Gen 3 mechanics.`,
```

2023-08-06 23:40 UTC, KrisXV commented on config/formats.ts
> +		mod: 'gen3hoenngaiden',
```suggestion
		],

		mod: 'gen3hoenngaiden',
```

2023-08-07 02:28 UTC, Yoshiblaze commented
> please fix all the build errors

Will do, but I'm not quite sure what the specific errors are. I assume they come from the learnsets.ts file since that's the one that was ignored by ESLint, but since it was ignored I'm not sure what to fix in there and I don't see any errors when I run it locally. Is there another way to see what specific errors there are?

2023-08-07 08:45 UTC, singiamtel commented
Running ``npm run full-test`` gives me around 10 typing errors

2023-08-07 13:29 UTC, Yoshiblaze commented
> Running `npm run full-test` gives me around 10 typing errors

Thank you, after doing this a few times I've now cleared all the errors.

2023-09-01 01:55 UTC, Yoshiblaze commented
Had to make some minor changes here and there over the last few weeks, but this should be good to go for September now with the build errors fixed, let me know if I missed anything

2023-09-01 04:27 UTC, KrisXV commented on data/mods/gen3hoenngaiden/pokedex.ts
> +		],
```suggestion
		otherFormes: ['Silvally-Bug', 'Silvally-Dark', 'Silvally-Dragon', 'Silvally-Electric', 'Silvally-Fighting', 'Silvally-Fire', 'Silvally-Flying', 'Silvally-Ghost', 'Silvally-Grass', 'Silvally-Ground', 'Silvally-Ice', 'Silvally-Poison', 'Silvally-Psychic', 'Silvally-Rock', 'Silvally-Steel', 'Silvally-Water'],
		formeOrder: ['Silvally', 'Silvally-Fighting', 'Silvally-Flying', 'Silvally-Poison', 'Silvally-Ground', 'Silvally-Rock', 'Silvally-Bug', 'Silvally-Ghost', 'Silvally-Steel', 'Silvally-Fire', 'Silvally-Water', 'Silvally-Grass', 'Silvally-Electric', 'Silvally-Psychic', 'Silvally-Ice', 'Silvally-Dragon', 'Silvally-Dark'],
```

2023-09-01 04:28 UTC, KrisXV approved these changes

2023-09-01 04:40 UTC, merged

2023-09-01 04:41 UTC, KrisXV commented
here's to hoping this doesnt explode