Update aliases.ts
smogon/pokemon-showdown pull request #9805
Opened 2023-09-26 05:27 UTC by SamirTacos

Added aliases from Alias Megathread

2023-09-26 05:35 UTC, KrisXV requested changes
I dont feel the need to comment on everything, but there are a lot of standards in this file as notated in the comments that got ignored with a lot of basic syntax errors that make it obvious that this wasnt tested locally, so im going to put this back into a draft for now

2023-09-26 05:35 UTC, KrisXV commented on data/aliases.ts
> +	compgen: "[Gen 9] Computer-Generated Teams",
i would prefer these to be near the rands formats

2023-09-26 05:35 UTC, KrisXV commented on data/aliases.ts
> +	megacruci: "Crucibelle-Mega",
maybe a new section for cap mons mightbe worth it? i dont wanna conflate cap and real pokemon

2023-09-26 05:35 UTC, KrisXV commented on data/aliases.ts
> +	mewtwoy, "Mewtwo-Mega-Y",
this isnt proper syntax

2023-09-26 05:35 UTC, KrisXV commented on data/aliases.ts
> +	venomicone: "Venomicon-Epilogue",
again, cap section

2023-09-26 05:35 UTC, KrisXV commented on data/aliases.ts
> +	ogerponwater: "Ogerpon-Wellspring-Tera",
this is the same entry twice

2023-09-26 05:35 UTC, KrisXV commented on data/aliases.ts
> +	ogerpontealtera: "Ogerpon-Teal-Tera",
this is the same thing

2023-09-26 05:35 UTC, KrisXV commented on data/aliases.ts
> +	venomiconprologue: "Venomicon",
cap thing

2023-09-26 05:35 UTC, KrisXV commented on data/aliases.ts
> +	ogerpongrass: "Ogerpon",
you already put these in earlier

2023-09-26 05:35 UTC, KrisXV commented on data/aliases.ts
> +	cc: "Covert Cloak",
this is already an alias for close combat

2023-09-26 05:35 UTC, KrisXV commented on data/aliases.ts
> +	colo: "Colossoil",
cap section

2023-09-26 05:35 UTC, KrisXV commented on data/aliases.ts
> +	cruci: "Crucibelle",
cap section

2023-09-26 05:35 UTC, KrisXV commented on data/aliases.ts
> +	ebook: "Venomicon-Epilogue",
cap section

2023-09-26 05:41 UTC, MathyFurret requested changes
quick pass

2023-09-26 05:41 UTC, MathyFurret commented on data/aliases.ts
> +	mewtwoy, "Mewtwo-Mega-Y",
```suggestion
	mewtwox: "Mewtwo-Mega-X",
	mewtwoy: "Mewtwo-Mega-Y",
```

2023-09-26 05:41 UTC, MathyFurret commented on data/aliases.ts
> +	cc: "Covert Cloak",
```suggestion
```
CC is already used for Close Combat

2023-09-26 05:41 UTC, MathyFurret commented on data/aliases.ts
> +	corvi: "Corviknight",
```suggestion
	corv: "Corviknight",
```
This is more common

2023-09-26 05:41 UTC, MathyFurret commented on data/aliases.ts
> +	tarrows, "Thousand Arrows",
```suggestion
	tarrows: "Thousand Arrows",
```

2023-09-26 05:41 UTC, MathyFurret commented on data/aliases.ts
> +	snael, "Snaelstrom",
```suggestion
	snael: "Snaelstrom",
```

2023-09-26 05:42 UTC, MathyFurret commented on data/aliases.ts
> +	cc: "Covert Cloak",
Could add "cloak" if you really want an alias for this

2023-09-26 06:03 UTC, MathyFurret commented on data/aliases.ts
> +	ogerpontealtera: "Ogerpon-Teal-Tera",
```suggestion
```
completely redundant alias

2023-09-26 06:07 UTC, smudgerox commented on data/aliases.ts
> +	valiant: "Iron Valiant",
"ival" and "val" are both very common shorthands for this mon

2023-09-26 06:10 UTC, smudgerox commented on data/aliases.ts
> +	blades: "Precipice Blades",
pblades is another good alias for this

2024-07-07 21:20 UTC, Zarel commented
Superseded by #10378

2024-07-07 21:20 UTC, closed without merging