Add New Pet Mod of the Season (VaporeMons) & Leader's Choice (Modern Gen 1)
smogon/pokemon-showdown pull request #9919
Opened 2023-11-24 22:26 UTC by Yoshiblaze

2023-11-24 23:54 UTC, Yoshiblaze commented
The next PMOTS and Leader's Choice were decided through a vote here https://www.smogon.com/forums/threads/pet-mod-of-the-season-voting.3731591/#post-9872133, which this PR adds in preparation for the December shifts in a week.

The removal of the folder of the previous PMOTS Hoenn Gaiden and Leader's Choice JolteMons Randbats weren't included as I inexplicably got a build error when trying to remove the former, but those both can be removed. 

This should have no build errors, but if anything comes up or if you have any questions or concerns then just let me know.

2023-12-01 07:17 UTC, KrisXV requested changes
can you delete the old mod files too please?

2023-12-01 07:17 UTC, KrisXV commented on config/formats.ts
> +		mod: 'vaporemons',
```suggestion

		mod: 'vaporemons',
```

2023-12-01 07:17 UTC, KrisXV commented on config/formats.ts
>  		],
```suggestion
		],

```

2023-12-01 07:17 UTC, KrisXV commented on data/mods/moderngen1/scripts.ts
> +			if (!this.data.Moves[i]) console.log(i);
```suggestion
```

2023-12-01 18:48 UTC, Yoshiblaze commented
Seems that for whatever reason, when running the check online, it tries to specifically check for all the files I deleted
![image](https://github.com/smogon/pokemon-showdown/assets/53023564/fea80ce4-2547-4087-a0bc-9bff442d049e)

Is there any way I can add the files back to this PR and then make a separate PR where I delete the old mods?

2023-12-01 20:12 UTC, Yoshiblaze commented
Have now made a separate pull request to remove the mods here https://github.com/smogon/pokemon-showdown/pull/9930, so this one won't have the build errors it had previously anymore.

2023-12-05 05:50 UTC, merged